/*
-- Query: SELECT * FROM brainrottranslator.dictionary
LIMIT 0, 1000

-- Date: 2024-11-14 15:42
*/
USE brainrottranslator;
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (1,'Skibidi','\"Skibidi\" has multiple meanings, including a Gen-Alpha slang term and a popular YouTube video series: \"Skibidi\" is a slang term that can be used as an adjective to mean cool, bad, or dumb, depending on the context. It can also be used to start a joking conversation. Colloquially, it can also mean good or best. YouTube video series:  \"Skibidi\" may also refer to a series of surrealist videos on YouTube that feature an army of toilets with human heads fighting against an army of men with camera heads. The series is popular with young people, Gen Z, and millennials for its blend of potty humor and absurdity.\nSong\n\"Skibidi\" is also the name of a song by Little Big that appears on the album Antipositive, Pt. 2. The song is in the genres of dance/electronic, pop, Russian dance, and French urban pop/R&B. It was nominated for Muz-TV Music Awards for Best Foreign Language Song and Best Video.','skibidi.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (2,'Brainrot','A term for when you become completely obsessed with something to the point it takes over your thoughts. First used online as early as 2004, the term \"brain rot\" grew in popularity by 2023 and evolved into an internet meme.','brainrot.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (3,'The Drink','\"The Drink\" is a term used to describe the character Trunks from the series Dragon Ball Z. It originates from a few videos from the YouTuber kobyshinobi, culminating in a music video: https://www.youtube.com/watch?v=DmW01hHGXgA','The_Drink.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (4,'Low-key','Low-key means subtly or secretly. \"I low-key like pineapples on pizza. I was low-key at the Diddy party.\"','low-key.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (5,'High-key','High-key means openly or intensely. \"I high-key like watching football.\" \"I high-key hate the government.\"','high-key.png');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (6,'Diddy','An american rapper known as \"P Diddy\" would frequently have lavish, exclusive parties. It\'s recently come out that his house was raided and what was found was 1000 bottles of baby oil, and it was found out who would use these to have \"freak-offs\" with his guests. This lead to Diddy being the current refrence for when something is \"freaky\".','diddy.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (7,'Based','Used to agree with or respect someone’s bold opinion, often if it goes against the norm. \"Yeah so I would suck the gas out of my employer\'s car and used it in mine since he stopped paying for mine.\" \"Based.\"','based.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (8,'Lit','Something is exciting or excellent. \"This party is lit!\"','lit.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (9,'Chad','A confident, successful man (often in the context of dating/attraction).','chad.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (10,'Giga chad','Refers to an exaggeratedly perfect or powerful man, often used humorously.','giga-chad.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (11,'Sigma male','A \"lone wolf\" archetype, someone who does their own thing, often seen as a counter to the \"alpha\" male.','sigma-male.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (12,'Sus',' Short for \"suspicious,\" often used when something seems off. Popularized by the hit game \"Among Us\".','among-us.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (13,'Vibing','Just chilling or enjoying the moment. The picture includes the \"Lofi Girl\" which was a 24/7 looping video of a girl doing homework while calming music played in the background.','vibing.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (14,'Rizz','Short for charisma, referring to someone\'s ability to charm or flirt.','rizz.png');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (15,'Bussin','Used to describe something that is really good, especially food.','bussin.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (16,'Gyatt','Exclamation: Used to express strong excitement, surprise, or admiration, especially in response to seeing a large butt or a voluptuous woman. For example, “Did you see the models in that video? GYATT”. Noun: Typically used to mean a large butt.','gyatt.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (17,'Bet','A term of agreement, like saying “okay” or “I’ll do it.” Example: \"No way can you hit all 5 pedestrians with your car.\" \"Bet.\"','bet.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (18,'Cap','Something you say when someone is lying. \"I swear I\'ve never seen them before in my life.\" \"Your honor that\'s cap.\"','cap.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (19,'No cap','Something you say to prove you aren\'t lying. \"I swear to you guys I was at the Diddy parties, no cap!\"','no-cap.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (20,'Flex','Showing off or bragging about something.','flex.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (21,'Flexing','Actively showing off or bragging about something.','weird_flex.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (22,'Fr','Short for “for real,” used to emphasize truthfulness.','fr.gif');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (23,'Finesse','To skillfully handle or manipulate a situation. To handle with grace and dignity. Can also mean to trick someone. \"Christopher Columbus finessed the Native Americans.\"','finesse.gif');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (24,'Im him','“I\'m him” is another way to assert your confidence and dominance. “I\'m him” is a show of confidence and bravado. It means that you\'re declaring yourself top dog. Saying “I\'m him” is like saying, “I\'m that guy.” Example: \"Dude are you sure you can just charge, screaming, into a police station to get your friend out of prison.\" \"Don\'t worry, I\'m him.\" ','Im-him.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (25,'Dank','High-quality, often used for memes or humor. \"That\'s such a dank meme.\" \"Fucking k--- yourself Gavin.\"','dank.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (26,'Low tier god','Internet celebrity most notited for saying the folowing. \"You have no life. You serve zero purpose. You should k--- yourself now.\"','lowtiergod.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (27,'Built different','Able to do things which others cannot; extremely talented or unusual. \"You sure you eat that hot pepper? They say it\'s the hottest in the world.\" \"That\'s nothing, I\'m built different.\"','built-different.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (28,'Aura','Used to describe someone\'s cool or “it” factor, and is often used to compliment someone\'s ability, perceived power, or sense of coolness and mystery. Can be seen as the new-gen term for swagger. ','loki-aura.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (29,'Bruh','Term used to express a feeling of shock, embarrassment, or disappointment toward something or someone.','bruh.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (30,'Blud','Another word for a \"friend\" or \"Bro\". It is often used to describe people or animals that are out of place.','blud.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (31,'Clapback','Swift and witty response to an insult or critique. Often emphasized with claps or clap emoji\'s.','clap-back.gif');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (32,'Cook','To \"cook\", as a verb, is to prepare or initiate a situation with the intent of creating a result. When a person says something smart you\'d say \"keep cooking\", if they said something incredibly stupid you\'d say \"never cook again\". When a person is \"cooked\", as an adjective, they are in the state of being in any sort of danger, physical, emotional, of failure, or of reputation.','never-cook-again.png');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (33,'Drip','Describes a cool outfit, if someone is wearing something cool they\'re \"dripped out\".','drip.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (34,'Fire','Term used to describe that something is impressive, good, or cool. \"This burrito is fire.\" ','fire.png');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (35,'Era','Term used to label a person\'s current interests or priorities. \"I totally entered my grief era when my grandma died.\"','grief.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (36,'Fit','Another word for outfit.','fit.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (37,'Hard','Another word for when something is cool or good. \"This edit goes hard af.\" \"That line goes hard.\" \"This pic goes hrad af.\"','hard.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (38,'Cold','Means something is \"cool\" or \"badass\". \"Yo that quote was so cold.\"','cold.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (39,'Nah Id win','Gojo, a character from the series \"Jujutusu Kaisen\", is asked if he would lose in the upcoming battle against the strongest sorcerer in history. To which he responds:','nah-id-win.png');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (40,'Gooner','Meaning someone is \"lost in the sauce\", a gooner is someone who looks at too much explicet content for his own good. ','lost-in-the-sauce.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (41,'Plug Walk','It is the type of walk that a plug, one who supplies illegal drugs, has. It is also a dance that coincides with the song “Plug Walk” by Rich the Kid.','pluh-walk.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (42,'Lock In','Focusing up. Can describe someone needing to get in \"the zone\".','parasyte-lock-in.gif');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (43,'L Bozo','\"L Bozo\" is an informal term that refers to a foolish or stupid person. \"L\" is usally short for lost or loser and \"Bozo\" is a name for a fool. You can also do \"Rip Bozo\" if the person lost or failed.','L-Bozo.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (44,'Clown','Clown is another term for an idiot or fool. \"Look at this clown.\"','clown.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (45,'Canon event','Taken from the movie \"Around the Spiderverse\", a canon event is a traumatic event that is fated to happen. \"Dude when harambe died that was my canon event.\"','canon-event.jpg');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (46,'Caught in 4K','Bro was caught in 4k','d');
INSERT INTO `dictionary` (`slangid`,`slang`,`defintion`,`imagename`) VALUES (47,'Fanum tax','Fanum tax (/fæn. əm. tæks/) is an Internet slang term describing the theft of food between friends. Originally coined by American streamer Fanum, the term has become an internet meme, particularly employed and popularized by Generation Alpha.','fanum_tax.jpg');
